config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations" }
  root 'home#index'

  resources :profiles
  get "/products", to: "products#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :shoppingcart
  belongs_to: product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :productcategory
  has_many :product, through: :productcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :shoppingcart
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :profile
  has_one :shoppingcart
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :profile
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :productorder
  has_many :product, through: :productorder
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cartitem
  has_many :shoppingcart, through: :cartitem
  
  has_many :productcategory
  has_many :category, through: :productcategory
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :location
  validates :phone_number, presence: true, length: {minimum: 10}
  validates :gender, presence: true
  validates :age, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :customer
  has_many :checkout
  
  has_many :cartitem
  has_many :product, thorugh: :cartitem
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
      @products = Product.all
      @categories = Category.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
      @profile = Profile.find(params[:id])

      if @profile.update(profile_params)
        redirect_to @root_path
      else
        redirect_to :edit
      end
    end

  private
  def profile_params
      params.require(:profile).permit(:phone_number, :gender, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QRO-E-Clothing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/header" %>
  <% if alert %>
    <p class="notice bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" "><%= notice %></p>
  <%end%>
    <% if alert %>
      <p class="alert bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"><%= alert %></p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.slim
header
    =link_to image_tag('logo.png'), root_path, class:'logo'
    nav
      ul.flex.justify-between.items-center.h-full.text-center.list-none.pr-3.5
        li.h-full.align-middle
           =link_to "home", root_path, class: 'flex justify-center items-center h-full text-white hover:text-black hover:bg-gray-200 transition-colors'
        - if customer_signed_in?
          li.h-full.align-middle
            =link_to "sign out",    destroy_customer_session_path, method: :delete, class: 'flex justify-center items-center h-full text-white hover:text-black hover:bg-gray-200 transition-colors'
          li.h-full.align-middle
            =link_to "account",   edit_customer_registration_path, class: 'flex justify-center items-center h-full text-white hover:text-black hover:bg-gray-200 transition-colors'
          li.h-full.align-middle.flex.justify-center.items-center.ml-2
              =link_to image_tag('shopping_cart.png'), root_path
          li.h-full.align-middle.flex.justify-center.items-center.ml-2
            span.bg-gray-200.rounded-full.w-6/12.text-black = current_customer.first_name[0] + " " + current_customer.last_name[0]
        - else 
          li.h-full.align-middle
            =link_to "sign up", new_customer_registration_path, class: 'flex justify-center items-center h-full text-white hover:text-black hover:bg-gray-200 transition-colors'
          li.h-full.align-middle
            =link_to "sign in",  customer_session_path, class: 'flex justify-center items-center h-full text-white hover:text-black hover:bg-gray-200 transition-colors'