config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations" }
  root 'home#index'

  resources :profiles
  get "/products", to: "products#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :shoppingcart
  belongs_to: product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :productcategory
  has_many :product, through: :productcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  belongs_to :shoppingcart
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :profile
  has_one :shoppingcart
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :profile
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :productorder
  has_many :product, through: :productorder
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cartitem
  has_many :shoppingcart, through: :cartitem
  
  has_many :productcategory
  has_many :category, through: :productcategory
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_one :location
  validates :phone_number, presence: true, length: {minimum: 10}
  validates :gender, presence: true
  validates :age, presence: true
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :customer
  has_many :checkout
  
  has_many :cartitem
  has_many :product, thorugh: :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  protected

  def after_sign_in_path_for(resource)
    if resource.sign_in_count == 1
      new_profile_path
    else
      root_path
    end
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
      @products = Product.all
      @categories = Category.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
      @profile = Profile.find(params[:id])

      if @profile.update(profile_params)
        redirect_to @root_path
      else
        redirect_to :edit
      end
    end

  private
  def profile_params
      params.require(:profile).permit(:phone_number, :gender, :age)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    new_customer_confirmation_path
  end
  
  
  private
    def customers_params
      params.require(:customer).permit(:password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.slim
.hero-section
  .hero-section-text
    h1.bg-white.bg-opacity-60.p-5.mx-auto.text-2xl.italic QRO e-clothing
    h2.bg-black.bg-opacity-80.p-4.mx-auto.text-white.tracking-wider.font-light The Best Clothing that Money Can buy.
    div.font-bold.tracking-widest.bg-blue-400.uppercase.mx-auto.mt-10.w-6/12.py-3.hover:bg-blue-800.hover:text-white
      =link_to "Catalog", products_path 
    

app/views/products/show.html.erb
<h1 class="mt-10 mb-5 text-2xl mb-7">Exclusive Clothing for The Refined</h1>

<div class="catalog-container py-8 px-5  form-container bg-gray-200 w-9/12 mx-auto text-center"

  <h2>Item Search</h2>
  <h2>Category Filter</h2>


  <%=select_tag(:phone_type, options_for_select(["Select One", "shirts", "pants", "socks"],:include_blank ["Select Category"])) %>


      <!-- product cards with add button -->
    <div class=" flex flex-wrap justify-start items-stretch gap-x-2.5 gap-y-2.5  w-11/12 mx-auto my-7">
        <% @products.each do |product| %>
          <div class="product-card flex flex-col items-stretch justify-between w-3/12 bg-white border-solid border-2 border-blue-100">
            <%=image_tag('product_images/' + product.image, class:"w-full")%>
            
            <div class="product-card_text w-full bg-gray-100 p-3">  
              <h3><%= product.name %></h3>
                <h6><strong>$<%= product.price %></strong></h6>
                <p><%= product.description %></p>
                <p><%= "available: #{product.unit_stock}" %></p>
                <p class="bg-blue-400 text-center text-white text-lg mt-2">+</p>
                <!--<%= button_to "+", class:"bg-blue-200" %>-->
              </div>
              
          </div>
        <% end %>
    </div>

</div>

#form_with(category) do |f|%>
   # f.select :id,  @categories.map{ |c| [c.name, c.id],}
#end%>

app/views/profiles/_form.html.erb
<div class="w-7/12 mx-auto">
    <%= form_with model: profile do |f| %>

      <div class="field mb-5">
        <%= f.label :phone_number %>
        <%= f.number_field :phone_number, class: "py-1 px-2" %>
        <% profile.errors.full_messages_for(:phone_number).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="field mb-5">
          <%= f.label :gender %>
          <%= f.select :gender, options_for_select(["Select One", "male", "female", "other"],:include_blank ["Select One"]), class: "py-1 px-2" %>
          <% profile.errors.full_messages_for(:gender).each do |message| %>
            <div><%= message %></div>
          <% end %>
      </div>

        <div>
          <%= f.label :age %>
          <%= f.number_field :age, class: "py-1 px-2" %>
          <% profile.errors.full_messages_for(:age).each do |message| %>
            <div><%= message %></div>
          <% end %>
      </div>

      <div>
        <%= f.submit  class: "py-2 px-1 mb-11 bg-black hover:bg-gray-800 w-3/12 text-white cursor-pointer mt-5" %>
      </div>

    <% end %>
</div>

app/views/profiles/edit.html.erb
<div class="text-center">
    <h1 class="mt-10 mb-5 text-2xl mb-7"><%= current_customer.first_name %></h1>
    <div class=" py-8 px-5  form-container bg-gray-200 w-9/12 mx-auto text-center">
      <h2 class="mb-5 text-2xl mb-7">Please update your Profile.</h2>

      <%= render "form", profile: @profile %>

    </div>

</div>

app/views/profiles/new.html.erb
<div class="text-center">
    <h1 class="mt-10 mb-5 text-2xl mb-7"><%= "Welcome, #{current_customer.first_name}!" %></h1>
    <div class=" py-8 px-5  form-container bg-gray-200 w-9/12 mx-auto text-center">
    <h2 class="mb-5 text-2xl mb-7">Please complete your Profile.</h2>

    <div class="w-7/12 mx-auto">
    <%= form_with model: @profile do |f| %>
      <div class="field mb-5">
        <%= f.label :phone_number %>
        <%= f.number_field :phone_number %>
        <% @profile.errors.full_messages_for(:phone_number).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="field mb-5">
        <%= f.label :gender %>
        <%= f.text_field :gender %>
        <% @profile.errors.full_messages_for(:gender).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

        <div>
        <%= f.label :age %>
        <%= f.number_field :age %>
        <% @profile.errors.full_messages_for(:age).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
      <%= f.submit "Create", class: "py-2 px-1 mb-11 bg-black hover:bg-gray-800 w-3/12 text-white cursor-pointer mt-5" %>
      </div>

    </div>
    <% end %>
    </div>

    </div>

</div>